services:
  windows:
    image: dockurr/windows:latest
    container_name: pc-virtual
    restart: unless-stopped

    environment:
      VERSION: "11"
      RAM_SIZE: "16G"
      CPU_CORES: "4"
      DISK_SIZE: "100G"
      USERNAME: "PC"
      PASSWORD: "TroqueEstaSenha123!"

    devices:
      - /dev/kvm
      - /dev/net/tun

    cap_add:
      - NET_ADMIN

    ports:
      - "8006:8006"
      - "3389:3389"

    volumes:
      - ./windows:/storage
